### ISSUE TITLE
Make Eclipse support more resilient

### ISSUE THREAD

**Issue by remmeier** [unbroken-dome/gradle-testsets-plugin#21]
It seem that the Eclipse plugin needs to be applied before the testset plugin. It would be helpful if that check whether Eclipse is applied could be deferred to a later stage in the execution and accept any order.

 In our project we apply quite a number of plugins and it starts to become tricky to set them up in the proper order for everything to work.

**Comment by Dispader** [comment]
Hey, @remmeier — In previous releases, I had some patching code for my builds to work around how source trees were getting built by the Eclipse plugin.  But I'm commenting because I've stopped using the Eclipse plugin entirely since Eclipse BuildShip became stable.

If you haven't tried BuildShip yet, I'd encourage you to give it a go.  If you haven't, though, may I ask why you're still using the Eclipse plugin?  I may be able to help, here.
