### ISSUE TITLE
How to add dependencies from integrationTest of another gradle module.

### ISSUE THREAD

**Issue by kowlown** [unbroken-dome/gradle-testsets-plugin#42]
Hello,
I have a case where I have a common module (ex : C) for the dao and two applications modules.
I need to write integration tests for the two different applications modules (A and B), but I want to have the injector used to initialize the database, in the common module.

How can I make the classes in C accessible from A and B ?

Regards.

**Comment by tkrullmann** [comment]
Hi,
if I understand you correctly you have an `integrationTest` testset in C which contains some tests in addition to shared test utils that you would like to reuse in other modules.

First, I would strongly suggest to move the shared code to a separate "test library" that contains no test but only utilities. Otherwise, with the default settings of JUnit or TestNG, you would run those tests in _every_ project that imports the library.

This scenario isn't something that the plugin covers directly. In general (without the plugin) you would follow these steps:
1. In project C:
  a) Create a source set for the test library (e.g. `testLib`)
  b) Create a Jar task that packages the test library (e.g. `testLibJar`)
  c) Create a configuration under which you will publish it (e.g. `testLib`)
  d) Declare an artifact that connects the configuration with the JAR
  e) optionally, if in project C you also have tests that depend on the testLib, use the testsets plugin and declare a dependency like this
      `integrationTestImplementation sourceSets.testLib.output`

Now, I suppose you _could_ probably use the test sets plugin to achieve part of this because it covers (a) and (b) and (d) for you, by making a `testSet` that doesn't actually contain any tests. However you would still need to do (c) yourself.

2. In projects A and B:
  a) use the test sets plugin
  b) Declare a dependency like
      `integrationTestImplementation project(path: ':C', configuration: 'testLib')`

So something like this (just jotting down, not tested code ;-) )

In project C
```groovy
// 1a
sourceSets { testLib }

// 1b
task testLibJar(type: Jar) {
    from sourceSets.testLib.output
}

// 1c
configurations { testLib }

// 1d
artifacts {
    testLib testLibJar
}

// 1e
dependencies {
    integrationTestImplementation sourceSets.testLib.output
}
```

When "abusing" the plugin:

```groovy
// 1c
configurations { testLib }

// 1a, 1b and 1d
testSets {
    testLib {
        publishArtifact = true
        artifactConfigurationName = 'testLib'
    }
}
```

It could definitely be easier, but this is not really the scenario the plugin tries to address. I've been thinking about how to allow something like test libraries in the plugin, but so far there is no direct support.
Hope that helps!

**Comment by kowlown** [comment]
Hi thank you for your answer.
My project C contains only shared test utils, no tests.
