### ISSUE TITLE
gradle 4.0+ test task not getting executed

### ISSUE THREAD

**Issue by jcamiloradamesa** [unbroken-dome/gradle-testsets-plugin#46]
Said you configure
```
testSets {
    itest
}
```
then when you execute `gradle itest` (in gradle 4.0+) task never get executed. `gradle itest -info` shows
```
Skipping task 'itest' as it has no source files and no previous output files.
```

**Comment by michaelcdillon** [comment]
@jcamiloradamesa did you get this resolved? If not, the reason the task is being skipped is because it has nothing to do: `Skipping task 'itest' as it has no source files and no previous output files.`

I would check that you have a folder in your src root named `itest` that contains either java or groovy test classes under it like this:
- Java example: `<src-root>/itest/java/com.package.testsuite/*Test.java`
- Groovy example: `<src-root>/itest/groovy/com.package.testsuite/*Test.groovy`

**Comment by tkrullmann** [comment]
Closing this as it's not an issue with the plugin.
