### ISSUE TITLE
How can I output to console information about failed test

### ISSUE THREAD

**Issue by vadger** [unbroken-dome/gradle-testsets-plugin#52]
Hello,

I'm trying to log to console information about failed integration test. The motivation is easy - to see information from console output without need to go html report in ci/cd.

with test task I can achieve it as:

```
test {
  testLogging {
    exceptionFormat = 'full'
  }
}
```

Thanks in advance.

**Comment by tkrullmann** [comment]
Hi,
the plugin will create a `Test` task for every test set that has the same name as the test set. So for example if your test set is called `integrationTest` you can configure the task like in your example (just put `integrationTest` instead of `test`).

Also, if you want to configure some behavior for _all_ `Test` tasks you can use the `withType` method from the tasks container:

```groovy
tasks.withType(Test) {
    testLogging.exceptionFormat = 'full'
}
```

Hope this helps!

**Comment by vadger** [comment]
Thanks it worked well.
