### ISSUE TITLE
Problem with testSets in multi project build

### ISSUE THREAD

**Issue by trohr** [unbroken-dome/gradle-testsets-plugin#58]
It seems to me, that there is problem when defining testSet with same name under multiple projects which are part of a multi-project build.

Example build.gradle:
```
plugins {
	id 'java'
	id 'org.unbroken-dome.test-sets' version '2.0.1'
}

testSets { integrationTest }

project (":subproject") {
	apply plugin: 'java'
	apply plugin: 'org.unbroken-dome.test-sets'
	testSets { integrationTest }
}
```

Such configuration makes the `integrationTestImplementation` configuration for the root project, but not for subproject `:subproject`.
Also the `integrationTest` task is created only for the root project but not for the subproject.

When I choose different name for the subproject's `integrationTest` test-set (e.g. `clientIntegrationTest`), than all works as expected.

My two cents,
Tomáš Rohrbacher

**Comment by tkrullmann** [comment]
Hi,

thanks for the report! I've never tried to configure subprojects like this, but I think it's a general issue with how Gradle / Groovy works.

What happens here is this:
- the plugin gets applied on the root project, creating a task called `integrationTest`
- in the subproject `testSets` block, you would usually just spell the name of the item to create, triggering `methodMissing` which in turn leads to Gradle creating the item. This is some of the Groovy magic that Gradle does.
- However, since `integrationTest` is already a known symbol in an enclosing scope (tasks are available as properties on the project), it will never trigger `methodMissing` on the testset container, but just use the task as an expression. Which, of course, does nothing.

If you replace `integrationTest` with `create('integrationTest')` in the subproject, then it will work. I'm afraid there isn't much I can do about it, it's just how Gradle works.

**Comment by trohr** [comment]
If I understand you correctly, one should define it the following way if indeed the subproject should have test-set with same name as test-set in root project:

```
plugins {
	id 'java'
	id 'org.unbroken-dome.test-sets' version '2.0.1'
}

testSets { integrationTest }

project (":subproject") {
	apply plugin: 'java'
	apply plugin: 'org.unbroken-dome.test-sets'
	testSets { create('integrationTest') }
}
```

Is that right?

Would you please be so kind as to document this in the Usage section of the documentation?

Thank you.

Tomas Rohrbacher
