### ISSUE TITLE
Prepend the classpath instead of appending it

### ISSUE THREAD

**Issue by fpavageau** [unbroken-dome/gradle-testsets-plugin#66]
In #55, there was a fix to concatenate the classpath of the test set to the existing test classpath, but this was done by appending to the test classpath (using `+=`).

I believe the correct behavior (as was present in 1.5.x) is to _prepend_ the test set classpath to the test classpath, so that there can be overrides in the test set (files with the same path, for example).

**Comment by fpavageau** [comment]
I'm interested in a release after the fix, by the way. 😄

**Comment by tkrullmann** [comment]
Hmm, I think this is still not right ;-)

Unfortunately the convention from Gradle's `JavaPlugin` adds test/java to the classpath of every `Test` task, not just the single task `test`.

Just accessing the classpath seems to trigger the convention, so we'll have the classes from `test` on every test set. Which is not the intention and might even lead to errors (e.g. issue #62).

So, I think the original issue #55 was wrongly fixed by modifying the classpath instead of replacing it; accessing its current value will always trigger the convention from JavaPlugin.

Instead, with the fix from 2.0.3 (commit 939a10b) I can revert this back to simply
```
task.classpath = sourceSet.runtimeClasspath
```

because the sourceSet's `runtimeClasspath` will already contain the main classes.

I'll open a new issue for this :-)
