### ISSUE TITLE
Generated Eclipse .classpath contains lib entries for 'build/classes/main' and 'build/resources/main'

### ISSUE THREAD

**Issue by kovax** [unbroken-dome/gradle-testsets-plugin#7]
These 2 entries should not be added to the .classpath file of Eclipse:

<classpathentry kind="lib" path="C:/Users/kovax/git/cristal-testing/build/classes/main" exported="true"/><classpathentry kind="lib" path="C:/Users/kovax/git/cristal-testing/build/resources/main" exported="true"/>

**Comment by unbroken-dome** [comment]
This seems to be a flaw in the eclipse plugin: If you create a reference from a configuration to a source set's output like so:

``` groovy
dependencies {
    integrationTestCompile sourceSets.main.output
}
```

Then the eclipse plugin will add extra "lib" entries for the main source set to the .classpath file. This is rather silly, because that source set is already contained via "src" entries.

So until this is fixed, I included a "workaround" in the testsets-plugin that removes these superfluous entries. It is equivalent to:

``` groovy
eclipse {
    classpath.file.whenMerged { classpath ->
        // Get all output directories for other source sets' classes and resources.
        def outputPaths = eclipseClasspath.project.sourceSets*.output
                .collect { [ it.classesDir, it.resourcesDir ]}
                .flatten { file -> Paths.get(file as String) } as Set
        classpath.entries.removeAll { ClasspathEntry entry ->
            entry.kind == 'lib' && Paths.get(entry.path) in outputPaths
        }
    }
}
```

**Comment by fmance** [comment]
@tkrullmann This seems to happen again for versions 2.x
