### ISSUE TITLE
Runtime Classpath of main Test sourceset being altered

### ISSUE THREAD

**Issue by adrianjgeorge** [unbroken-dome/gradle-testsets-plugin#78]
I'm using gradle 4.10, but I've duplicated the problem on gradle 5.5.1 as well.
I was attempting to migrate from 1.42 to 2.1.1 as part of a migration in my build to 5.5.1.
As part of my build I take any `compileOnly` dependencies and add them to the classpath of all other source sets.
https://github.com/rackerlabs/repose/blob/master/build.gradle#L274-L291
I had no problems with this in 1.4.2 (I also checked 1.5.2 which also works), but in 2.1.1 my runtime  classpath changes on the normal test source set no longer work. They appear to be removed or otherwise ignored when using the new version of your plugin. 
The changes to the classpath are completely hosing a super large set of my tests.

I'd be ahppy to provide whatever else you might need to get this resolved.

**Comment by tkrullmann** [comment]
Hi,
I'm not sure what the issue is here, but have you tried using proper dependencies instead of directly modifying the source set classpath? That's very low-level, and it looks like you're replicating a lot of the work that Gradle would do for you anyway with its configurations and dependencies constructs.

So for example, instead of
```groovy
sourceSets {
    // ...
    test {
        compileClasspath += configurations.compileOnly
        runtimeClasspath += configurations.compileOnly
        compileClasspath += files([sourceSets.generated.java.outputDir])
        runtimeClasspath += files([sourceSets.generated.java.outputDir])
    }
}
```

try declaring these as dependencies in the `dependencies` block:

```groovy
dependencies {
    implementation sourceSets.generated.output
}
```

Then you also don't need to repeat this for the test and integrationTest classpath, because `testImplementation` extends the `implementation` configuration, and `integrationTestImplementation` in turn extends the `testImplementation` configuration.

If you want to have the `compileOnly` dependencies available in tests, you should just add an `extendsFrom` statement on the configuration:
```groovy
configurations {
    testCompileOnly.extendsFrom(compileOnly)
}
```

The test-sets plugin automatically does this for test sets (so `integrationTestCompileOnly` automatically inherits dependencies from `testCompileOnly`).

The plugin shouldn't directly modify the classpath of the `test` source set in any way, if it does it's probably a bug. The Gradle file you linked to is quite huge, it would help if you could provide a smaller sample file that illustrates the behavior you mean.
