### ISSUE TITLE
Using Unit Test (Base) Class in Integration Test

### ISSUE THREAD

**Issue by bikusta** [unbroken-dome/gradle-testsets-plugin#8]
First of all, I'm not sure if it's a bug or intended behavior. 

I have this test set in my build file:

```
testSets {
  integrationTest
}
```

Furthermore, I defined a base class in the unit test source set and another base class in the integration test source set that derives from the unit test base class. When trying to compile the integration tests, I get a compiler error saying 'unable to resolve class'. 

Compilation works as soon as I add this:

```
sourceSets {
  integrationTest {
    compileClasspath += sourceSets.test.output
    runtimeClasspath += sourceSets.test.output
  }
}
```

As said, I'm not sure if the plugin should behave like that. If yes, it might be helpful to extend the documentation, just in case someone has a similar scenario.

**Comment by unbroken-dome** [comment]
Hi,

no, the plugin currently only adds dependencies to the main source set automatically. The reasons for that are (I guess):
- From a conceptual point of view, the "unit test" set shouldn't really stand out in any way.
- Unit tests and integration tests are some quite different concepts; they shouldn't really have anything in common. If you want to share some test helper or base classes, you might want to put them into yet another source set and have both test sets depend on it.
- In addition, you might want to package your integration tests in a separate JAR (the plugin can create an artifact for this), and an implicit dependency to "test" would get in the way.

Thank you for the hint, I will add some clarification to the readme.

By the way, it is better to declare the dependency on the other source set by:

``` groovy
dependencies {
    integrationTestCompile sourceSets.test.output
}
```

This way, you save the extra line for the runtime dependency because integrationTestRuntime inherits it from integrationTestCompile.
