### ISSUE TITLE
Gradle 6 support

### ISSUE THREAD

**Issue by tkrullmann** [unbroken-dome/gradle-testsets-plugin#92]
The plugin should work in Gradle 6.

Currently when running in Gradle 5 there are a couple of deprecation warnings that will turn into errors in Gradle 6.

**Comment by cmdcarini** [comment]
Looks like this is ready to go (https://github.com/unbroken-dome/gradle-testsets-plugin/pull/94), could @tkrullmann or someone else with write access merge? Would be nice to have Gradle 6 support.

**Comment by adamu** [comment]
#94 fixes one of the warnings, but there is also #98 which fixes both.

**Comment by dgeissl** [comment]
@tkrullmann any news on the issue?
Gradle 6 has matured to version 6.1.1, I guess many projects want to try it out but are hold back by the incompatibility of the testsets plugin. Or should anyone interested in Gradle 6 follow the mentioned gradle/gradle#11273 ?

**Comment by HelLViS69** [comment]
Hello,
I'm using this plugin since 3 years. Never had a problem until Gradle 5.6.4, when it started to fail builds until Gradle 6.1, then I updated to Gradle 6.2 and started working again. I'm now using Gradle 6.3 and no problems here (also I switched to JUnit 5 some days ago)

Forgot to mention: I have a multi-module project

**Comment by tkrullmann** [comment]
Version 3.0 will improve support for Gradle 6.x and drop support for Gradle 4.x
